const puppeteer = require(process.env.PUPPETEER_MODULE || 'puppeteer-core');
const fs=require('fs');
(async()=>{const browser=await puppeteer.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
const page=await browser.newPage(); const results=[];
for(const width of [1280,390]){await page.setViewport({width,height:900});await page.goto(process.env.AUDIT_URL||'https://akaslany.github.io/ai-intel/2026-10-02/',{waitUntil:'networkidle2'});
results.push(await page.evaluate((width)=>{const root=document.querySelector('.ai-intel-report'); const labels=[];const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n,previous=null;
function rect(node,start,end){const r=document.createRange();r.setStart(node,start);r.setEnd(node,end);const b=r.getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:b.height};}
while(n=walker.nextNode()){const re=/Evidence(?=\s*[:ABC])|(?:일차 )?출처(?: URL)?(?=\s*:)/g;let m;while(m=re.exec(n.textContent)){let prev=null;const prefix=n.textContent.slice(0,m.index);if(prefix.trim()){const end=prefix.trimEnd().length;prev=rect(n,end-1,end);}else if(previous){prev=rect(previous,previous.textContent.trimEnd().length-1,previous.textContent.trimEnd().length);}const current=rect(n,m.index,m.index+m[0].length);labels.push({label:m[0],text:n.textContent.slice(0,140),current,prev,lower:!prev||current.y>prev.y+1});}if(n.textContent.trim())previous=n;}
const anchors=[...root.querySelectorAll('a[href^="http"]')].map(a=>{a.scrollIntoView({block:'center',inline:'center'});const r=a.getBoundingClientRect();const x=Math.max(0,Math.min(innerWidth-1,r.x+r.width/2)),y=Math.max(0,Math.min(innerHeight-1,r.y+r.height/2));const hit=document.elementFromPoint(x,y);return {href:a.getAttribute('href'),width:r.width,height:r.height,pointer:getComputedStyle(a).pointerEvents,hit:hit===a||a.contains(hit),valid:/^https?:\/\//.test(a.href)};});
const bare=[];const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(n=w.nextNode())if(/https?:\/\//.test(n.textContent)&&!n.parentElement.closest('a'))bare.push(n.textContent);
return {width,url:location.href,labels,anchors,bare,text:root.innerText};},width));}
fs.writeFileSync(process.env.AUDIT_OUT||`${process.env.TMPDIR || process.cwd()}/ai-dom-audit.json`,JSON.stringify(results,null,2));
console.log(JSON.stringify(results.map(r=>({width:r.width,labels:r.labels.length,inline:r.labels.filter(x=>!x.lower).map(x=>x.text),anchors:r.anchors.length,badAnchors:r.anchors.filter(a=>!a.hit||!a.valid||!a.width||!a.height||a.pointer==='none'),bare:r.bare})),null,2));
for(const r of results){if(r.labels.some(x=>!x.lower)||r.bare.length||r.anchors.some(a=>!a.hit||!a.valid||!a.width||!a.height||a.pointer==='none'))throw Error('DOM presentation audit failed at '+r.width);if(process.env.EXPECT_LABELS&&r.labels.length!==Number(process.env.EXPECT_LABELS))throw Error('label count mismatch');if(process.env.EXPECT_ANCHORS&&r.anchors.length!==Number(process.env.EXPECT_ANCHORS))throw Error('anchor count mismatch');}
if(process.env.CLICK==='1'){const url=results[0].anchors.find(a=>a.href.includes('arxiv.org')).href;await page.goto(process.env.AUDIT_URL,{waitUntil:'networkidle2'});const selector=`.ai-intel-report a[href="${url}"]`;await page.$eval(selector,a=>a.scrollIntoView());await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded',timeout:45000}).catch(e=>console.log('navigation timeout '+e.message)),page.click(selector)]);console.log('ACTUAL_CLICK '+page.url());if(!page.url().startsWith(url))throw Error('Click did not navigate');}
await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
